substitutions:
  name_add_mac_suffix: 'true'
  node_name: boneio

esphome:
  name: ${node_name}
  platform: ESP32
  board: nodemcu-32s
  # set to false if you already added this device to ESPHOME add-on
  name_add_mac_suffix: ${name_add_mac_suffix}
  project:
    name: boneio.32x10-lights
    version: '1.0'
ethernet:
  id: eth
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

dashboard_import:
  package_import_url: github://boneIO-eu/esphome/boneio-lights_v0_7.yaml@single_file_test
  import_full_config: true

packages:
  internals_packages:
    url: https://github.com/boneIO-eu/esphome
    ref: single_file_test
    files:
      [
        'devices/buzzer.yaml',
#        'devices/display.yaml',
        'devices_v0_7/i2c.yaml',
        'devices/ina219.yaml',
        'devices/lm75b.yaml',
        'devices/one_wire.yaml',
        'devices_v0_7/pcf.yaml',
        'devices/uart_v_0_7.yaml',
        'boards_v_0_7/32x10_outputs.yaml',
      ]

logger:
api:
ota:
  password: boneio

web_server:
  port: 80
  local: true

time:
  - platform: homeassistant
    timezone: Europe/Warsaw
    id: homeassistant_time

light:
  - platform: binary
    name: 'OUT 1'
    output: out_1
  - platform: binary
    name: 'OUT 2'
    output: out_2
  - platform: binary
    name: 'OUT 3'
    output: out_3
  - platform: binary
    name: 'OUT 4'
    output: out_4
  - platform: binary
    name: 'OUT 5'
    output: out_5
  - platform: binary
    name: 'OUT 6'
    output: out_6
  - platform: binary
    name: 'OUT 7'
    output: out_7
  - platform: binary
    name: 'OUT 8'
    output: out_8
  - platform: binary
    name: 'OUT 9'
    output: out_9
  - platform: binary
    name: 'OUT 10'
    output: out_10
  - platform: binary
    name: 'OUT 11'
    output: out_11
  - platform: binary
    name: 'OUT 12'
    output: out_12
  - platform: binary
    name: 'OUT 13'
    output: out_13
  - platform: binary
    name: 'OUT 14'
    output: out_14
  - platform: binary
    name: 'OUT 15'
    output: out_15
  - platform: binary
    name: 'OUT 16'
    output: out_16
  - platform: binary
    name: 'OUT 17'
    output: out_17
  - platform: binary
    name: 'OUT 18'
    output: out_18
  - platform: binary
    name: 'OUT 19'
    output: out_19
  - platform: binary
    name: 'OUT 20'
    output: out_20
  - platform: binary
    name: 'OUT 21'
    output: out_21
  - platform: binary
    name: 'OUT 22'
    output: out_22
  - platform: binary
    name: 'OUT 23'
    output: out_23
  - platform: binary
    name: 'OUT 24'
    output: out_24
  - platform: binary
    name: 'OUT 25'
    output: out_25
  - platform: binary
    name: 'OUT 26'
    output: out_26
  - platform: binary
    name: 'OUT 27'
    output: out_27
  - platform: binary
    name: 'OUT 28'
    output: out_28
  - platform: binary
    name: 'OUT 29'
    output: out_29
  - platform: binary
    name: 'OUT 30'
    output: out_30
  - platform: binary
    name: 'OUT 31'
    output: out_31
  - platform: binary
    name: 'OUT 32'
    output: out_32
